language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
- "./ci/doc.js"
after_success:
- "./ci/travis/publish.js"
env:
  secure: trsr3rUAQXnDdunThDnRmG3j5is2YwTXl6VdCCBsdgqvHBKhBB6O8J1ZQUpxHCOAeRls0Aua1h8V75PV9WU/rscHBMzA/ZEulFakDKiKBgZtQaK2xdXUiEFaW7PKBDX6hDbFlvCJsxvEuxzfg1MphYLwqGFP0FWpL0UwzyC/KrnXum69kmAKEUJIIPzXLPH5RKsD/rE1b6MlsWAN2B0RlTHGgp5tOntGSBKNYE9dz6bW5b3V9eaZpyqTvDrkKOQbVsuMf+Za8otlwjEVtlceZmfSiaVJKF+xDJQpXM3Rn9Hjf3Q2LKUVTmcp055SSK+bfqzH/TS8gSRXP/ovi3T5RFz/9L1nGyVNa76acM2LjyzyRlK/StezxIKUIfJqGgjU8mUveSDGYzgwopJm912x5bgIfO+CtxTzNMhZPNMV6G/F3YuZ0LH1oblhR/wX5RPeZly4LgiBvj+d6bhvVHcuFRjkshfkDmE3AZDJwoAgqEKbeQYPbgjuaJfLcH+E9V1MDcGqwdtizoMkkjJjLc9FVMA+X7ND0fLcwirVM6mn0ntj+WkE8Rdaz+rf6si7jxQlT0G7aZJ0XXyK5HvqzoHnNQ4Zsjhkr9kGUz3EHSxYGbyIFbsnZ2AE9A659zp2vNenxYfqYiV8UwSXoISHguOCCw87GNJZiVukhMUN1+2N7eg=
  global:
    secure: Riay4sniqpJi7JstE3RCc8lV5OJFImC4ITEVn/O4ggJfH4TJJtoXqwL5s62Cc8h6lLzb10Xv2TTFWdBhP21lXlPnRSUOuT4dziXsciyfiGbICsZ0urLfTCmwbt0Ousirx9yw6G4VLDxtQgfmmdNJUl0BhQzSH5vWeW/5U5No//eXBrQiYuTpf5HGS3hIsVeM1y2a1uVNIMKXRTIfQpwk95q1O+Bfj8yHShIpv6gkVoymVR4YZWcRj9+TAjxJf+VxIvlk2VXXHos/ytIcG9f1b8DeU5547o3KLCr57L7xNlPlUAdvdpe3kjqLmUn6WtD+yk8tcz7mfY/U5XFdnfPlj0li6iNCEdXz01yFC7YrmsPY8HzA+hpDut46sAYSbUji0N8QJ4wmd6huVDZDSH0+y6z4UQMSG/oBhCDSb4BTXOrNnam98tlkbSfQkXUZ88rCzEv3ITBcBxNwUY75HIB5O+BqRA0ZZjsX4qNWyBIIeFZPqwk6ayvW6kzjeckspiMEGKRre/cM10B9/pi2CgUpCdWoyo3+jQZ6DKqaxWj0/4xXI+CojWEDPGGyeaWmgTodL3nA4mh+IaKD473TDiDVhfBeq8vEm1pKTT+ouDxPkS5afuCGKHdltTYu9+06sjuMCcRnF0UKuBXuvQ3wyXYRIIpNN5mKXXlXUsrycGMcc/M=
